name: cwnet
channels:
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.3.11
  - cuda-nvcc=11.8.89
  - cudatoolkit=11.8.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.14
  - packaging=23.2
  - pip=24.0
  - python=3.8.19
  - readline=8.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.1.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - albucore==0.0.17
      - albumentations==1.4.18
      - annotated-types==0.7.0
      - argparse==1.4.0
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==23.2.0
      - automat==22.10.0
      - backcall==0.2.0
      - basicsr==1.4.2
      - bitsandbytes==0.44.1
      - buildtools==1.0.6
      - cachetools==5.5.0
      - causal-conv1d==1.1.1
      - certifi==2022.12.7
      - cfgv==3.4.0
      - charset-normalizer==2.1.1
      - colorama==0.4.6
      - constantly==23.10.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.1.1
      - distlib==0.3.9
      - docopt==0.6.2
      - einops==0.8.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - facexlib==0.3.0
      - filelock==3.13.1
      - filterpy==1.4.5
      - fonttools==4.53.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.2.3
      - furl==2.1.3
      - future==1.0.0
      - google-auth==2.36.0
      - google-auth-oauthlib==1.0.0
      - greenlet==3.0.3
      - grpcio==1.67.1
      - h5py==3.11.0
      - huggingface-hub==0.23.4
      - hyperlink==21.0.0
      - icecream==2.1.3
      - identify==2.6.2
      - idna==3.4
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.0
      - incremental==22.10.0
      - iniconfig==2.0.0
      - ipdb==0.13.13
      - ipython==8.12.3
      - jedi==0.19.1
      - jinja2==3.1.3
      - kiwisolver==1.4.5
      - kornia==0.7.3
      - kornia-rs==0.1.4
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - llvmlite==0.41.1
      - lmdb==1.5.1
      - lpips==0.1.4
      - mamba-ssm==1.1.3.post1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.5
      - mpmath==1.3.0
      - multidict==6.1.0
      - natsort==8.4.0
      - networkx==3.0
      - ninja==1.11.1.1
      - nodeenv==1.9.1
      - numba==0.58.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - openai-clip==1.0.1
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.10.0.84
      - orderedmultidict==1.0.1
      - pandas==2.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==4.0.1
      - prompt-toolkit==3.0.47
      - propcache==0.2.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - ptflops==0.7.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.18.0
      - pyiqa==0.1.13
      - pyparsing==3.1.2
      - pytest==8.3.3
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.4.0
      - pytorch-ssim==0.1
      - pytz==2024.2
      - pywavelets==1.4.1
      - pyyaml==6.0.1
      - redo==2.0.4
      - regex==2024.5.15
      - requests==2.28.1
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rsa==4.9
      - safetensors==0.4.3
      - scikit-image==0.21.0
      - scipy==1.10.1
      - seaborn==0.13.2
      - segment-anything==1.0
      - sentencepiece==0.2.0
      - simplejson==3.19.2
      - six==1.16.0
      - sqlalchemy==2.0.31
      - stack-data==0.6.3
      - sympy==1.12
      - tb-nightly==2.14.0a20230808
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - thop==0.1.1-2209072238
      - tifffile==2023.7.10
      - timm==1.0.7
      - tokenizers==0.15.2
      - tomli==2.0.1
      - torch==2.1.1+cu118
      - torchaudio==2.1.1+cu118
      - torchmetrics==1.5.2
      - torchsummaryx==1.3.0
      - torchvision==0.16.1+cu118
      - tqdm==4.66.4
      - traitlets==5.14.3
      - transformers==4.37.2
      - triton==2.1.0
      - twisted==24.3.0
      - typing-extensions==4.13.2
      - tzdata==2024.2
      - urllib3==1.26.13
      - virtualenv==20.27.1
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.15.2
      - zipp==3.20.2
      - zope-interface==6.4.post2
