#### general settings
name: train
use_tb_logger: false
model: enhancement_model
distortion: sr
scale: 1
gpu_ids: [1]
seg: true
clip_type: CLIP

#### datasets
datasets:
  train:
    name: ll_dataset
    interval_list: [1]
    random_reverse: false
    border_mode: false

    invention_num: 2
    # your light map path
    lightmap_GT :  
    # your image path
    dataroot_GT: 
    dataroot_LQ: 

    n_workers: 3  # per GPU
    batch_size: 8
    GT_size: 256   # size you want to crop out as input sample.
    LQ_size: 256
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: ll_dataset
    # your image path
    dataroot_GT: 
    dataroot_LQ: 

    train_size: [600, 400]

#### network structures
network_G:
  which_model_G: CWNet
  nf: 16 # 32 # 64
  n_l_blocks: [1,3,3,3,1]
  n_h_blocks: [1,2,2,2,1]

#### path
path:
  root: ./
  strict_load: false

#### training settings: learning rate scheme, loss
train:
  lr_G: 0.0004
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 300000
  lr_steps: [130000, 180000]
  ft_tsa_only: 0
  warmup_iter: -1  # -1: no warm up
  lr_gamma: 0.5
  eta_min: !!float 1e-7
  vgg_loss: true
  pixel_criterion: l2
  pixel_weight: 1.0
  val_freq: !!float 1e3

  manual.resize960x512_seed: 0

#### logger
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1000
